import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface ExportDataParams {
  kpis: {
    today_revenue: number;
    today_orders: number;
    today_avg_order: number;
  };
  stockAlertCount: number;
  revenueTrend: {
    day_label: string;
    day_date: string;
    total_revenue: number;
  }[];
  lowStockItems: {
    item_id: string;
    item_name: string;
    category_name: string;
    current_stock: number;
    low_stock_threshold: number;
    unit: string;
  }[];
  recentActivity: {
    id: string;
    user_name: string;
    action: string;
    target_name: string | null;
    target_type: string | null;
    created_at: string;
  }[];
  dayOffset: number;
  chartImageBase64: string | null;
  logoImageBase64?: string | null;
  profileName: string;
}

export function generateDashboardPDF(data: ExportDataParams) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const BRAND_COLOR: [number, number, number] = [194, 69, 106]; // #C2456A
  const TEXT_COLOR: [number, number, number] = [60, 60, 60];
  const LIGHT_TEXT: [number, number, number] = [120, 120, 120];

  // Determine Title
  let reportTitle = "Daily Sales & Operations Report";
  if (data.revenueTrend.length > 1) {
    if (data.revenueTrend.length === 7) {
      reportTitle = "Weekly Sales & Operations Report";
    } else {
      reportTitle = "Custom Sales & Operations Report";
    }
  }

  // Determine Period
  let periodStr = "";
  if (data.revenueTrend.length >= 2) {
    const start = new Date(data.revenueTrend[0].day_date);
    const end = new Date(data.revenueTrend[data.revenueTrend.length - 1].day_date);
    periodStr = `${start.toLocaleDateString("en-PH", { month: "long", day: "numeric", year: "numeric" })} – ${end.toLocaleDateString("en-PH", { month: "long", day: "numeric", year: "numeric" })}`;
  } else if (data.revenueTrend.length === 1) {
    const start = new Date(data.revenueTrend[0].day_date);
    periodStr = start.toLocaleDateString("en-PH", { month: "long", day: "numeric", year: "numeric" });
  } else {
    periodStr = new Date().toLocaleDateString("en-PH", { month: "long", day: "numeric", year: "numeric" });
  }

  const generatedOn = new Date().toLocaleDateString("en-PH", { month: "long", day: "numeric", year: "numeric" });

  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 15;

  let cursorY = 20;

  // Header Cover
  if (data.logoImageBase64) {
    doc.addImage(data.logoImageBase64, "PNG", margin, cursorY - 7, 10, 10);
    doc.setFontSize(22);
    doc.setTextColor(...BRAND_COLOR);
    doc.setFont("helvetica", "bold");
    doc.text("Sheilz Coffee", margin + 13, cursorY);
  } else {
    doc.setFontSize(22);
    doc.setTextColor(...BRAND_COLOR);
    doc.setFont("helvetica", "bold");
    doc.text("Sheilz Coffee", margin, cursorY);
  }

  cursorY += 10;
  doc.setFontSize(16);
  doc.setTextColor(...TEXT_COLOR);
  doc.text(reportTitle, margin, cursorY);

  cursorY += 12;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Reporting Period:", margin, cursorY);
  doc.setFont("helvetica", "normal");
  doc.text(periodStr, margin + 35, cursorY);

  cursorY += 6;
  doc.setFont("helvetica", "bold");
  doc.text("Generated On:", margin, cursorY);
  doc.setFont("helvetica", "normal");
  doc.text(generatedOn, margin + 35, cursorY);

  cursorY += 6;
  doc.setFont("helvetica", "bold");
  doc.text("Generated By:", margin, cursorY);
  doc.setFont("helvetica", "normal");
  doc.text(data.profileName || "Administrator", margin + 35, cursorY);

  // Line separator
  cursorY += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);

  cursorY += 12;

  // Executive Summary
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_COLOR);
  doc.text("Executive Summary", margin, cursorY);
  cursorY += 10;

  // Cards layout
  const cardWidth = (pageWidth - margin * 2 - 15) / 4;

  const drawCard = (x: number, y: number, title: string, value: string) => {
    doc.setDrawColor(220, 220, 220);
    doc.setFillColor(250, 250, 250);
    doc.roundedRect(x, y, cardWidth, 25, 2, 2, "FD");

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...LIGHT_TEXT);
    doc.text(title, x + 5, y + 8);

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...TEXT_COLOR);
    doc.text(value, x + 5, y + 18);
  };

  const revenueStr = `PHP ${data.kpis.today_revenue.toLocaleString("en-PH", { minimumFractionDigits: 2 })}`;
  const ordersStr = `${data.kpis.today_orders}`;
  const avgOrderStr = `PHP ${data.kpis.today_avg_order.toLocaleString("en-PH", { minimumFractionDigits: 2 })}`;
  const alertsStr = `${data.stockAlertCount}`;

  drawCard(margin, cursorY, "Total Revenue", revenueStr);
  drawCard(margin + cardWidth + 5, cursorY, "Total Orders", ordersStr);
  drawCard(margin + cardWidth * 2 + 10, cursorY, "Avg Order Value", avgOrderStr);
  drawCard(margin + cardWidth * 3 + 15, cursorY, "Stock Alerts", alertsStr);

  cursorY += 35;

  // Dashboard Summary text
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...TEXT_COLOR);

  const summaryText = `During the selected reporting period, the store generated ${revenueStr} in revenue from ${ordersStr} completed orders, resulting in an average order value of ${avgOrderStr}. There are currently ${alertsStr} inventory items flagged as low stock. Recent administrative activity indicates normal operational usage, including administrator logins and inventory updates.`;

  const splitSummary = doc.splitTextToSize(summaryText, pageWidth - margin * 2);
  doc.text(splitSummary, margin, cursorY);
  cursorY += splitSummary.length * 5 + 10;

  // Revenue Trend Chart
  if (data.chartImageBase64) {
    if (cursorY + 80 > pageHeight - 20) {
      doc.addPage();
      cursorY = 20;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND_COLOR);
    doc.text("Revenue Trend", margin, cursorY);
    cursorY += 8;

    doc.addImage(data.chartImageBase64, "PNG", margin, cursorY, pageWidth - margin * 2, 60);
    cursorY += 65;
  }

  // Revenue Trend Table
  const tableData = data.revenueTrend.map((d) => [
    d.day_label,
    new Date(d.day_date).toLocaleDateString("en-PH"),
    `PHP ${Number(d.total_revenue).toLocaleString("en-PH", { minimumFractionDigits: 2 })}`,
  ]);

  if (tableData.length > 0) {
    autoTable(doc, {
      startY: cursorY,
      head: [["Day", "Date", "Revenue"]],
      body: tableData,
      theme: "grid",
      headStyles: { fillColor: BRAND_COLOR },
      styles: { fontSize: 9 },
      margin: { left: margin, right: margin, bottom: 30 },
    });
    cursorY = (doc as any).lastAutoTable.finalY + 15;
  }

  // Low Stock
  if (data.lowStockItems.length > 0) {
    if (cursorY + 30 > pageHeight - 20) {
      doc.addPage();
      cursorY = 20;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND_COLOR);
    doc.text("Low Stock Items", margin, cursorY);
    cursorY += 5;

    const lowStockTableData = data.lowStockItems.map((item) => {
      const ratio = item.current_stock / item.low_stock_threshold;
      let status = "OK";
      if (ratio <= 0.25) status = "Critical";
      else if (ratio <= 0.5) status = "Low";
      return [
        item.item_name,
        `${item.current_stock} / ${item.low_stock_threshold} ${item.unit}`,
        status,
      ];
    });

    autoTable(doc, {
      startY: cursorY,
      head: [["Ingredient", "Remaining", "Status"]],
      body: lowStockTableData,
      theme: "grid",
      headStyles: { fillColor: BRAND_COLOR },
      styles: { fontSize: 9 },
      didParseCell: function (data) {
        if (data.section === "body" && data.column.index === 2) {
          const status = data.cell.raw;
          if (status === "Critical") {
            data.cell.styles.textColor = [220, 38, 38];
            data.cell.styles.fontStyle = "bold";
          } else if (status === "Low") {
            data.cell.styles.textColor = [217, 119, 6];
            data.cell.styles.fontStyle = "bold";
          }
        }
      },
      margin: { left: margin, right: margin, bottom: 30 },
    });

    cursorY = (doc as any).lastAutoTable.finalY + 15;
  }

  // Recent Activity
  if (data.recentActivity.length > 0) {
    if (cursorY + 30 > pageHeight - 20) {
      doc.addPage();
      cursorY = 20;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND_COLOR);
    doc.text("Recent Activity", margin, cursorY);
    cursorY += 5;

    const activityTableData = data.recentActivity.map((item) => {
      let desc = item.action;
      if (item.target_name) {
        desc += ` (${item.target_type ? item.target_type + ": " : ""}${item.target_name})`;
      }
      return [
        desc,
        item.user_name,
        new Date(item.created_at).toLocaleString("en-PH"),
      ];
    });

    autoTable(doc, {
      startY: cursorY,
      head: [["Activity Description", "User", "Timestamp"]],
      body: activityTableData,
      theme: "grid",
      headStyles: { fillColor: BRAND_COLOR },
      styles: { fontSize: 9 },
      margin: { left: margin, right: margin, bottom: 30 },
    });
  }

  // Add Headers & Footers to all pages
  const totalPages = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "normal");

    doc.text("Sheilz Coffee POS", margin, pageHeight - 20);
    doc.text(reportTitle, margin, pageHeight - 15);
    doc.text(`Generated On: ${generatedOn}`, margin, pageHeight - 10);
    
    // Page X of Y aligned to right
    const pageStr = `Page ${i} of ${totalPages}`;
    const pageStrWidth = doc.getTextWidth(pageStr);
    doc.text(pageStr, pageWidth - margin - pageStrWidth, pageHeight - 10);
  }

  // Save the PDF
  const filename = `${reportTitle.replace(/\s+/g, "_")}_${generatedOn.replace(/,/g, "").replace(/\s+/g, "_")}.pdf`;
  doc.save(filename);
}
