import * as ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import { InventoryItem, Category, getInventoryStatus } from "../data";

export interface AppliedFilters {
  search: string;
  category: string;
  showLowStockOnly: boolean;
}

const PRIMARY_COLOR = "FFC2456A";

function getStatusColor(status: string): string {
  switch (status) {
    case "Healthy":
      return "FF10B981"; // Emerald 500
    case "Low Stock":
      return "FFF59E0B"; // Amber 500
    case "Critical Stock":
      return "FFEF4444"; // Red 500
    case "Out of Stock":
      return "FF991B1B"; // Red 800
    default:
      return "FF6B7280"; // Gray 500
  }
}

const headerStyle: Partial<ExcelJS.Style> = {
  font: { bold: true, color: { argb: "FFFFFFFF" } },
  fill: {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: PRIMARY_COLOR },
  },
  alignment: { vertical: "middle", horizontal: "center" },
  border: {
    top: { style: "thin", color: { argb: "FFCCCCCC" } },
    left: { style: "thin", color: { argb: "FFCCCCCC" } },
    bottom: { style: "thin", color: { argb: "FFCCCCCC" } },
    right: { style: "thin", color: { argb: "FFCCCCCC" } },
  },
};

const borderStyle: Partial<ExcelJS.Borders> = {
  top: { style: "thin", color: { argb: "FFEEEEEE" } },
  left: { style: "thin", color: { argb: "FFEEEEEE" } },
  bottom: { style: "thin", color: { argb: "FFEEEEEE" } },
  right: { style: "thin", color: { argb: "FFEEEEEE" } },
};

export async function exportInventoryToExcel(
  items: InventoryItem[],
  categories: Category[],
  filters: AppliedFilters,
  currentDate: Date = new Date(),
) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Sheilz Coffee POS";
  wb.created = currentDate;
  wb.modified = currentDate;

  const categoryMap = new Map(categories.map((c) => [c.id, c.name]));
  const getCategoryName = (id: string) => categoryMap.get(id) || "Uncategorized";

  // Formatter for date
  const dateStr = currentDate.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  if (items.length === 0) {
    const ws = wb.addWorksheet("Inventory Summary");
    ws.getCell("A1").value = "Sheilz Coffee";
    ws.getCell("A1").font = { size: 20, bold: true, color: { argb: PRIMARY_COLOR } };
    ws.getCell("A2").value = "Inventory Report";
    ws.getCell("A2").font = { size: 14, bold: true, color: { argb: "FF4B5563" } };
    ws.getCell("A4").value = "Generated On";
    ws.getCell("B4").value = dateStr;
    ws.getCell("A6").value = "No inventory records were found for the selected filters.";
    ws.getCell("A6").font = { italic: true, color: { argb: "FF6B7280" } };
    ws.getColumn("A").width = 30;
    ws.getColumn("B").width = 20;
    await downloadWorkbook(wb, filters, dateStr, getCategoryName);
    return;
  }

  // --- Worksheet 1: Inventory Summary ---
  const ws1 = wb.addWorksheet("Inventory Summary");
  ws1.getColumn("A").width = 25;
  ws1.getColumn("B").width = 35;

  ws1.getCell("A1").value = "Sheilz Coffee";
  ws1.getCell("A1").font = { size: 20, bold: true, color: { argb: PRIMARY_COLOR } };
  ws1.getCell("A2").value = "Inventory Report";
  ws1.getCell("A2").font = { size: 14, bold: true, color: { argb: "FF4B5563" } };

  ws1.getCell("A4").value = "Generated On";
  ws1.getCell("B4").value = dateStr;
  ws1.getCell("A5").value = "Generated By";
  ws1.getCell("B5").value = "System User";
  ws1.getCell("A6").value = "Branch";
  ws1.getCell("B6").value = "Main Branch";

  // Formatting basic info
  ["A4", "A5", "A6"].forEach((cell) => {
    ws1.getCell(cell).font = { bold: true };
    ws1.getCell(cell).alignment = { horizontal: "left" };
  });

  const lowCriticalCount = items.filter((i) => {
    const s = getInventoryStatus(i);
    return s === "Low Stock" || s === "Critical Stock" || s === "Out of Stock";
  }).length;
  const uniqueCategories = new Set(items.map((i) => i.categoryId)).size;

  ws1.getCell("A8").value = "Inventory KPI Summary";
  ws1.getCell("A8").font = { size: 12, bold: true, color: { argb: PRIMARY_COLOR } };

  ws1.getCell("A9").value = "Total Ingredients";
  ws1.getCell("B9").value = items.length;
  ws1.getCell("A10").value = "Attention Needed (Low/Critical)";
  ws1.getCell("B10").value = lowCriticalCount;
  ws1.getCell("A11").value = "Total Categories";
  ws1.getCell("B11").value = uniqueCategories;

  ["A9", "A10", "A11"].forEach((cell) => {
    ws1.getCell(cell).font = { bold: true };
  });
  ["B9", "B10", "B11"].forEach((cell) => {
    ws1.getCell(cell).alignment = { horizontal: "left" };
  });

  ws1.getCell("A13").value = "Applied Filters";
  ws1.getCell("A13").font = { size: 12, bold: true, color: { argb: PRIMARY_COLOR } };

  // Filter Table
  ws1.getCell("A14").value = "Filter";
  ws1.getCell("B14").value = "Value";
  ws1.getRow(14).eachCell((cell, colNumber) => {
    if (colNumber <= 2) cell.style = headerStyle as ExcelJS.Style;
  });

  ws1.getCell("A15").value = "Search";
  ws1.getCell("B15").value = filters.search || "(None)";
  ws1.getCell("A16").value = "Category";
  ws1.getCell("B16").value =
    filters.category === "all" ? "All Items" : getCategoryName(filters.category);
  ws1.getCell("A17").value = "Low Stock Only";
  ws1.getCell("B17").value = filters.showLowStockOnly ? "Yes" : "No";

  [15, 16, 17].forEach((rowNum) => {
    ws1.getRow(rowNum).getCell(1).font = { bold: true };
    ws1.getRow(rowNum).eachCell((cell, colNum) => {
      if (colNum <= 2) cell.border = borderStyle as ExcelJS.Borders;
    });
  });

  // --- Worksheet 2: Current Inventory ---
  const ws2 = wb.addWorksheet("Current Inventory", {
    views: [{ state: "frozen", ySplit: 1 }],
  });
  ws2.columns = [
    { header: "Ingredient", key: "name", width: 30 },
    { header: "Category", key: "category", width: 25 },
    { header: "Unit", key: "unit", width: 10 },
    { header: "Current Stock", key: "currentStock", width: 18 },
    { header: "Threshold", key: "threshold", width: 15 },
    { header: "Maximum Stock", key: "maxCapacity", width: 18 },
    { header: "Stock Status", key: "status", width: 18 },
  ];

  ws2.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  items.forEach((item) => {
    const status = getInventoryStatus(item);
    const row = ws2.addRow({
      name: item.name,
      category: getCategoryName(item.categoryId),
      unit: item.unit,
      currentStock: item.currentStock,
      threshold: item.lowStockThreshold,
      maxCapacity: item.maxCapacity,
      status: status,
    });

    row.eachCell((cell) => {
      cell.border = borderStyle as ExcelJS.Borders;
    });

    // Style the status cell
    const statusCell = row.getCell("status");
    statusCell.font = { bold: true, color: { argb: getStatusColor(status) } };

    // Highlight stock value if below threshold
    if (status !== "Healthy") {
      row.getCell("currentStock").font = { bold: true, color: { argb: "FF991B1B" } };
    }
  });

  // Add auto filter to the table
  ws2.autoFilter = `A1:G${items.length + 1}`;

  // Add Data Bar Conditional Formatting on Column D (Current Stock)
  
  ws2.addConditionalFormatting({
  ref: `D2:D${items.length + 1}`,
  rules: [
    {
      type: "dataBar",
      cfvo: [{ type: "min" }, { type: "max" }],
      color: { argb: PRIMARY_COLOR },
    } as any,
  ],
});

  // --- Worksheet 3: Inventory by Category ---
  const ws3 = wb.addWorksheet("Inventory by Category");
  ws3.columns = [
    { header: "Category", key: "category", width: 25 },
    { header: "Total Items", key: "total", width: 15 },
    { header: "Healthy", key: "healthy", width: 15 },
    { header: "Low Stock", key: "low", width: 15 },
    { header: "Critical", key: "critical", width: 15 },
    { header: "Out of Stock", key: "oos", width: 15 },
  ];

  ws3.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  const categoryStats = new Map<string, { t: number; h: number; l: number; c: number; o: number }>();
  items.forEach((item) => {
    const cName = getCategoryName(item.categoryId);
    const s = getInventoryStatus(item);
    if (!categoryStats.has(cName)) {
      categoryStats.set(cName, { t: 0, h: 0, l: 0, c: 0, o: 0 });
    }
    const stats = categoryStats.get(cName)!;
    stats.t++;
    if (s === "Healthy") stats.h++;
    if (s === "Low Stock") stats.l++;
    if (s === "Critical Stock") stats.c++;
    if (s === "Out of Stock") stats.o++;
  });

  const sortedCategories = Array.from(categoryStats.entries()).sort((a, b) =>
    a[0].localeCompare(b[0])
  );

  let rowIdx = 2;
  sortedCategories.forEach(([cName, stats]) => {
    const row = ws3.addRow({
      category: cName,
      total: stats.t,
      healthy: stats.h,
      low: stats.l,
      critical: stats.c,
      oos: stats.o,
    });
    row.eachCell((cell) => {
      cell.border = borderStyle as ExcelJS.Borders;
    });
    rowIdx++;
  });

  // Totals Row using formulas
  const totalsRow = ws3.addRow({
    category: "TOTALS",
    total: { formula: `SUM(B2:B${rowIdx - 1})` },
    healthy: { formula: `SUM(C2:C${rowIdx - 1})` },
    low: { formula: `SUM(D2:D${rowIdx - 1})` },
    critical: { formula: `SUM(E2:E${rowIdx - 1})` },
    oos: { formula: `SUM(F2:F${rowIdx - 1})` },
  });
  totalsRow.font = { bold: true };
  totalsRow.eachCell((cell) => {
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFF3F4F6" },
    };
    cell.border = borderStyle as ExcelJS.Borders;
  });

  // --- Worksheet 4: Low & Critical Stock Report ---
  const ws4 = wb.addWorksheet("Low & Critical Stock", {
    views: [{ state: "frozen", ySplit: 1 }],
  });
  ws4.columns = [
    { header: "Ingredient", key: "name", width: 30 },
    { header: "Category", key: "category", width: 25 },
    { header: "Current Stock", key: "current", width: 18 },
    { header: "Threshold", key: "threshold", width: 15 },
    { header: "Difference", key: "diff", width: 15 },
    { header: "Status", key: "status", width: 18 },
  ];
  ws4.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  const lowStockItems = items
    .filter((i) => getInventoryStatus(i) !== "Healthy")
    .sort((a, b) => {
      const diffA = a.currentStock - a.lowStockThreshold;
      const diffB = b.currentStock - b.lowStockThreshold;
      return diffA - diffB;
    });

  if (lowStockItems.length === 0) {
    ws4.getCell("A2").value = "No low or critical stock items found.";
    ws4.getCell("A2").font = { italic: true, color: { argb: "FF6B7280" } };
  } else {
    lowStockItems.forEach((item) => {
      const status = getInventoryStatus(item);
      const row = ws4.addRow({
        name: item.name,
        category: getCategoryName(item.categoryId),
        current: item.currentStock,
        threshold: item.lowStockThreshold,
        diff: item.currentStock - item.lowStockThreshold,
        status: status,
      });

      row.eachCell((cell) => {
        cell.border = borderStyle as ExcelJS.Borders;
      });

      const statusCell = row.getCell("status");
      statusCell.font = { bold: true, color: { argb: getStatusColor(status) } };

      const diffCell = row.getCell("diff");
      diffCell.font = { color: { argb: "FFEF4444" }, bold: true };
    });
    ws4.autoFilter = `A1:F${lowStockItems.length + 1}`;
  }

  // --- Worksheet 5: Inventory Statistics ---
  const ws5 = wb.addWorksheet("Inventory Statistics");
  ws5.columns = [
    { header: "Metric", key: "metric", width: 35 },
    { header: "Value", key: "val", width: 15 },
    { header: "Percentage", key: "pct", width: 15 },
  ];
  ws5.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  let totalH = 0;
  let totalL = 0;
  let totalC = 0;
  let totalO = 0;

  items.forEach((i) => {
    const s = getInventoryStatus(i);
    if (s === "Healthy") totalH++;
    if (s === "Low Stock") totalL++;
    if (s === "Critical Stock") totalC++;
    if (s === "Out of Stock") totalO++;
  });

  const statsData = [
    { metric: "Total Inventory Items", val: items.length, pct: 1 },
    { metric: "Healthy Items", val: totalH, pct: items.length ? totalH / items.length : 0 },
    { metric: "Low Stock Items", val: totalL, pct: items.length ? totalL / items.length : 0 },
    { metric: "Critical Items", val: totalC, pct: items.length ? totalC / items.length : 0 },
    { metric: "Out of Stock Items", val: totalO, pct: items.length ? totalO / items.length : 0 },
    { metric: "Number of Categories", val: uniqueCategories, pct: null },
  ];

  statsData.forEach((stat) => {
    const row = ws5.addRow(stat);
    row.eachCell((cell) => {
      cell.border = borderStyle as ExcelJS.Borders;
    });
    row.getCell("metric").font = { bold: true };
    const pctCell = row.getCell("pct");
    if (stat.pct !== null) {
      pctCell.numFmt = "0.00%";
    } else {
      pctCell.value = "-";
      pctCell.alignment = { horizontal: "right" };
    }
  });

  // Footer for all sheets
  wb.eachSheet((sheet) => {
    sheet.headerFooter = {
      oddFooter: `&LSheilz Coffee POS - Inventory Report&CGenerated On ${dateStr}&RPage &P of &N`,
    };
  });

  await downloadWorkbook(wb, filters, dateStr, getCategoryName);
}

async function downloadWorkbook(
  wb: ExcelJS.Workbook,
  filters: AppliedFilters,
  dateStr: string,
  getCategoryName: (id: string) => string
) {
  const buffer = await wb.xlsx.writeBuffer();
  
  let catName = "All_Items";
  if (filters.category !== "all") {
    catName = getCategoryName(filters.category).replace(/\s+/g, "_"); 
  }
  
  // Format YYYY-MM-DD
  const isoDate = new Date().toISOString().split("T")[0];
  let fileName = `Inventory_Report_${isoDate}.xlsx`;
  
  if (filters.category !== "all") {
    fileName = `Inventory_Report_${catName}_${isoDate}.xlsx`;
  }

  saveAs(new Blob([buffer]), fileName);
}