import * as ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import { InventoryTransaction, InventoryItem, TransactionType } from "../data";

const PRIMARY_COLOR = "FFC2456A"; // Sheilz Coffee Primary Color

function getTypeColor(type: TransactionType | string): string {
  switch (type) {
    case "Replenishment":
      return "FF10B981"; // Emerald 500 (Green)
    case "Automatic POS Deduction":
      return "FF3B82F6"; // Blue 500
    case "Manual Adjustment":
      return "FFF59E0B"; // Amber 500 (Orange)
    case "Stock Correction":
      return "FFA855F7"; // Purple 500
    case "Waste / Spoilage":
      return "FFEF4444"; // Red 500
    default:
      return "FF6B7280"; // Gray 500
  }
}

const headerStyle: Partial<ExcelJS.Style> = {
  font: { bold: true, color: { argb: "FFFFFFFF" } },
  fill: {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: PRIMARY_COLOR },
  },
  alignment: { vertical: "middle", horizontal: "center" },
  border: {
    top: { style: "thin", color: { argb: "FFCCCCCC" } },
    left: { style: "thin", color: { argb: "FFCCCCCC" } },
    bottom: { style: "thin", color: { argb: "FFCCCCCC" } },
    right: { style: "thin", color: { argb: "FFCCCCCC" } },
  },
};

const borderStyle: Partial<ExcelJS.Borders> = {
  top: { style: "thin", color: { argb: "FFEEEEEE" } },
  left: { style: "thin", color: { argb: "FFEEEEEE" } },
  bottom: { style: "thin", color: { argb: "FFEEEEEE" } },
  right: { style: "thin", color: { argb: "FFEEEEEE" } },
};

export async function exportLedgerToExcel(
  transactions: InventoryTransaction[],
  items: InventoryItem[],
  timeFilter: string,
  currentDate: Date = new Date()
) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Sheilz Coffee POS";
  wb.created = currentDate;
  wb.modified = currentDate;

  const itemMap = new Map(items.map((i) => [i.id, i]));
  const getItemName = (id: string) => itemMap.get(id)?.name || "Unknown";
  const getItemUnit = (id: string) => itemMap.get(id)?.unit || "";

  const dateStr = currentDate.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  if (transactions.length === 0) {
    const ws = wb.addWorksheet("Ledger Summary");
    ws.getCell("A1").value = "Sheilz Coffee";
    ws.getCell("A1").font = { size: 20, bold: true, color: { argb: PRIMARY_COLOR } };
    ws.getCell("A2").value = "Inventory Ledger Report";
    ws.getCell("A2").font = { size: 14, bold: true, color: { argb: "FF4B5563" } };
    ws.getCell("A4").value = "Generated On";
    ws.getCell("B4").value = dateStr;
    ws.getCell("A6").value = "No inventory ledger records were found for the selected filters.";
    ws.getCell("A6").font = { italic: true, color: { argb: "FF6B7280" } };
    ws.getColumn("A").width = 30;
    ws.getColumn("B").width = 20;
    await downloadWorkbook(wb, timeFilter);
    return;
  }

  // Calculate stats for Summary
  let replenishments = 0;
  let posDeductions = 0;
  let manualAdjustments = 0;
  let totalDeliveryCost = 0;
  const affectedIngredients = new Set<string>();

  transactions.forEach((t) => {
    affectedIngredients.add(t.ingredientId);
    if (t.type === "Replenishment") replenishments++;
    if (t.type === "Automatic POS Deduction") posDeductions++;
    if (t.type === "Manual Adjustment") manualAdjustments++;
    if (t.expenseDetails?.deliveryCost) totalDeliveryCost += t.expenseDetails.deliveryCost;
  });

  // --- Worksheet 1: Ledger Summary ---
  const ws1 = wb.addWorksheet("Ledger Summary");
  ws1.getColumn("A").width = 30;
  ws1.getColumn("B").width = 25;

  ws1.getCell("A1").value = "Sheilz Coffee";
  ws1.getCell("A1").font = { size: 20, bold: true, color: { argb: PRIMARY_COLOR } };
  ws1.getCell("A2").value = "Inventory Ledger Report";
  ws1.getCell("A2").font = { size: 14, bold: true, color: { argb: "FF4B5563" } };

  ws1.getCell("A4").value = "Generated On";
  ws1.getCell("B4").value = dateStr;
  ws1.getCell("A5").value = "Generated By";
  ws1.getCell("B5").value = "System User";
  ws1.getCell("A6").value = "Branch";
  ws1.getCell("B6").value = "Main Branch";
  ws1.getCell("A7").value = "Selected Time Range";
  ws1.getCell("B7").value = timeFilter;

  ["A4", "A5", "A6", "A7"].forEach((cell) => {
    ws1.getCell(cell).font = { bold: true };
    ws1.getCell(cell).alignment = { horizontal: "left" };
  });

  ws1.getCell("A9").value = "Ledger KPI Summary";
  ws1.getCell("A9").font = { size: 12, bold: true, color: { argb: PRIMARY_COLOR } };

  const kpis = [
    { label: "Ledger Entries", val: transactions.length, isCurrency: false },
    { label: "Replenishments", val: replenishments, isCurrency: false },
    { label: "POS Deductions", val: posDeductions, isCurrency: false },
    { label: "Manual Adjustments", val: manualAdjustments, isCurrency: false },
    { label: "Delivery Cost", val: totalDeliveryCost, isCurrency: true },
    { label: "Ingredients Updated", val: affectedIngredients.size, isCurrency: false },
  ];

  let rIdx = 10;
  kpis.forEach((kpi) => {
    ws1.getCell(`A${rIdx}`).value = kpi.label;
    ws1.getCell(`A${rIdx}`).font = { bold: true };
    const valCell = ws1.getCell(`B${rIdx}`);
    valCell.value = kpi.val;
    if (kpi.isCurrency) {
      valCell.numFmt = "₱#,##0.00";
    }
    rIdx++;
  });

  ws1.getCell(`A${rIdx + 1}`).value = "Applied Filters";
  ws1.getCell(`A${rIdx + 1}`).font = { size: 12, bold: true, color: { argb: PRIMARY_COLOR } };

  ws1.getCell(`A${rIdx + 2}`).value = "Filter";
  ws1.getCell(`B${rIdx + 2}`).value = "Value";
  ws1.getRow(rIdx + 2).eachCell((cell, colNumber) => {
    if (colNumber <= 2) cell.style = headerStyle as ExcelJS.Style;
  });

  const filtersTable = [
    { filter: "Time Range", val: timeFilter },
    { filter: "Generated On", val: dateStr },
    { filter: "Generated By", val: "System User" },
  ];
  let filterRow = rIdx + 3;
  filtersTable.forEach((f) => {
    ws1.getCell(`A${filterRow}`).value = f.filter;
    ws1.getCell(`A${filterRow}`).font = { bold: true };
    ws1.getCell(`B${filterRow}`).value = f.val;
    ws1.getRow(filterRow).eachCell((cell, colNumber) => {
      if (colNumber <= 2) cell.border = borderStyle as ExcelJS.Borders;
    });
    filterRow++;
  });

  // --- Worksheet 2: Inventory Ledger ---
  const ws2 = wb.addWorksheet("Inventory Ledger", {
    views: [{ state: "frozen", ySplit: 1 }],
  });
  ws2.columns = [
    { header: "Date & Time", key: "date", width: 25 },
    { header: "Ingredient", key: "ingredient", width: 25 },
    { header: "Movement Type", key: "type", width: 25 },
    { header: "Stock Change", key: "change", width: 15 },
    { header: "New Stock", key: "newStock", width: 15 },
    { header: "Unit", key: "unit", width: 10 },
    { header: "Delivery Cost", key: "cost", width: 15 },
    { header: "Payment Method", key: "payment", width: 15 },
  ];

  ws2.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  transactions.forEach((txn) => {
    const row = ws2.addRow({
      date: new Date(txn.date),
      ingredient: getItemName(txn.ingredientId),
      type: txn.type,
      change: txn.quantityChanged,
      newStock: txn.newStock,
      unit: getItemUnit(txn.ingredientId),
      cost: txn.expenseDetails?.deliveryCost || 0,
      payment: txn.expenseDetails?.paymentMethod || "-",
    });

    row.getCell("date").numFmt = "mmm d, yyyy h:mm am/pm";
    const typeCell = row.getCell("type");
    typeCell.font = { bold: true, color: { argb: getTypeColor(txn.type) } };

    const changeCell = row.getCell("change");
    changeCell.numFmt = "+#,##0;-#,##0;0";
    changeCell.font = {
      bold: true,
      color: { argb: txn.quantityChanged > 0 ? "FF10B981" : txn.quantityChanged < 0 ? "FFEF4444" : "FF6B7280" },
    };

    row.getCell("newStock").numFmt = "#,##0";
    row.getCell("cost").numFmt = "₱#,##0.00";

    row.eachCell((cell) => {
      cell.border = borderStyle as ExcelJS.Borders;
    });
  });
  ws2.autoFilter = `A1:H${transactions.length + 1}`;

  // --- Worksheet 3: Movement Summary ---
  const ws3 = wb.addWorksheet("Movement Summary");
  ws3.columns = [
    { header: "Movement Type", key: "type", width: 30 },
    { header: "Count", key: "count", width: 15 },
  ];
  ws3.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  const typeCounts = new Map<string, number>();
  transactions.forEach((t) => {
    typeCounts.set(t.type, (typeCounts.get(t.type) || 0) + 1);
  });
  
  let ws3Row = 2;
  Array.from(typeCounts.entries()).forEach(([type, count]) => {
    const row = ws3.addRow({ type, count });
    row.getCell("type").font = { bold: true, color: { argb: getTypeColor(type) } };
    row.eachCell((cell) => {
      cell.border = borderStyle as ExcelJS.Borders;
    });
    ws3Row++;
  });
  
  const ws3TotalsRow = ws3.addRow({
    type: "TOTAL",
    count: { formula: `SUM(B2:B${ws3Row - 1})` }
  });
  ws3TotalsRow.font = { bold: true };
  ws3TotalsRow.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF3F4F6" } };
    cell.border = borderStyle as ExcelJS.Borders;
  });


  // --- Worksheet 4: Ingredient Movement Summary ---
  const ws4 = wb.addWorksheet("Ingredient Movement Summary", { views: [{ state: "frozen", ySplit: 1 }] });
  ws4.columns = [
    { header: "Ingredient", key: "ingredient", width: 30 },
    { header: "Total Movements", key: "count", width: 20 },
    { header: "Net Stock Change", key: "net", width: 20 },
  ];
  ws4.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  const ingStats = new Map<string, { count: number; net: number }>();
  transactions.forEach((t) => {
    const name = getItemName(t.ingredientId);
    if (!ingStats.has(name)) ingStats.set(name, { count: 0, net: 0 });
    const stat = ingStats.get(name)!;
    stat.count++;
    stat.net += t.quantityChanged;
  });

  const sortedIngs = Array.from(ingStats.entries()).sort((a, b) => b[1].count - a[1].count);
  sortedIngs.forEach(([name, stat]) => {
    const row = ws4.addRow({
      ingredient: name,
      count: stat.count,
      net: stat.net,
    });
    row.getCell("net").numFmt = "+#,##0;-#,##0;0";
    row.getCell("net").font = {
      bold: true,
      color: { argb: stat.net > 0 ? "FF10B981" : stat.net < 0 ? "FFEF4444" : "FF6B7280" },
    };
    row.eachCell((cell) => {
      cell.border = borderStyle as ExcelJS.Borders;
    });
  });


  // --- Worksheet 5: Replenishment Report ---
  const ws5 = wb.addWorksheet("Replenishment Report", { views: [{ state: "frozen", ySplit: 1 }] });
  ws5.columns = [
    { header: "Date", key: "date", width: 20 },
    { header: "Ingredient", key: "ingredient", width: 30 },
    { header: "Quantity Added", key: "added", width: 18 },
    { header: "New Stock", key: "newStock", width: 15 },
    { header: "Delivery Cost", key: "cost", width: 18 },
    { header: "Payment Method", key: "payment", width: 20 },
  ];
  ws5.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  const replens = transactions.filter((t) => t.type === "Replenishment");
  if (replens.length === 0) {
    ws5.getCell("A2").value = "No replenishments found in this time range.";
    ws5.getCell("A2").font = { italic: true, color: { argb: "FF6B7280" } };
  } else {
    let ws5Row = 2;
    replens.forEach((t) => {
      const row = ws5.addRow({
        date: new Date(t.date),
        ingredient: getItemName(t.ingredientId),
        added: t.quantityChanged,
        newStock: t.newStock,
        cost: t.expenseDetails?.deliveryCost || 0,
        payment: t.expenseDetails?.paymentMethod || "-",
      });
      row.getCell("date").numFmt = "mmm d, yyyy";
      row.getCell("added").numFmt = "#,##0";
      row.getCell("newStock").numFmt = "#,##0";
      row.getCell("cost").numFmt = "₱#,##0.00";
      row.eachCell((cell) => {
        cell.border = borderStyle as ExcelJS.Borders;
      });
      ws5Row++;
    });

    // Totals Row
    const rTotals = ws5.addRow({
      date: "TOTALS",
      ingredient: "",
      added: { formula: `SUM(C2:C${ws5Row - 1})` },
      newStock: "", // sum of new stock doesn't make sense
      cost: { formula: `SUM(E2:E${ws5Row - 1})` },
      payment: "",
    });
    rTotals.font = { bold: true };
    rTotals.getCell("cost").numFmt = "₱#,##0.00";
    rTotals.getCell("added").numFmt = "#,##0";
    rTotals.eachCell((cell) => {
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF3F4F6" } };
      cell.border = borderStyle as ExcelJS.Borders;
    });
    
    ws5.autoFilter = `A1:F${replens.length + 1}`;
  }

  // Footer for all sheets
  wb.eachSheet((sheet) => {
    sheet.headerFooter = {
      oddFooter: `&LSheilz Coffee POS - Inventory Ledger Report&CGenerated On ${dateStr}&RPage &P of &N`,
    };
  });

  await downloadWorkbook(wb, timeFilter);
}

async function downloadWorkbook(wb: ExcelJS.Workbook, preset: string) {
  const buffer = await wb.xlsx.writeBuffer();
  
  const isoDate = new Date().toISOString().split("T")[0];
  const safePreset = preset.replace(/[\s\/]+/g, "_");
  
  const fileName = `Inventory_Ledger_Report_${safePreset}_${isoDate}.xlsx`;
  
  saveAs(new Blob([buffer]), fileName);
}
