import ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import { Customer } from "./mock-data";

interface ExportOptions {
  customers: Customer[];
  allCustomersLength: number;
  reportScope: string;
  adminName: string;
  settings: {
    purchasesRequired: number;
    reward: string;
    rewardQuantity: number;
    enabled: boolean;
  };
}

export const exportCustomersToExcel = async (options: ExportOptions) => {
  const { customers, allCustomersLength, reportScope, adminName, settings } = options;

  // Initialize Workbook
  const workbook = new ExcelJS.Workbook();
  workbook.creator = adminName;
  workbook.lastModifiedBy = adminName;
  workbook.created = new Date();
  workbook.modified = new Date();

  const brandColor = "C2456A";
  const headerFontColor = "FFFFFF";
  const lightBgColor = "FBE4EA"; // lighter shade for accents
  const neutralBgColor = "F3F4F6";

  // =========================================================================
  // WORKSHEET 1: Customer Records
  // =========================================================================
  const ws1 = workbook.addWorksheet("Customer Records", {
    views: [{ state: "frozen", xSplit: 0, ySplit: 11 }]
  });

  // --- Report Header ---
  ws1.mergeCells("A1:K1");
  const titleCell = ws1.getCell("A1");
  titleCell.value = "Sheilz Coffee - Customer Management Report";
  titleCell.font = { name: "Calibri", size: 18, bold: true, color: { argb: headerFontColor } };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: brandColor } };
  titleCell.alignment = { vertical: "middle", horizontal: "center" };

  // Metadata
  const now = new Date();
  const dateString = now.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "2-digit" });
  const timeString = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });

  ws1.getCell("A3").value = "Generated on:";
  ws1.getCell("B3").value = `${dateString} ${timeString}`;
  ws1.getCell("A4").value = "Generated by:";
  ws1.getCell("B4").value = adminName;
  ws1.getCell("A5").value = "Report Scope:";
  ws1.getCell("B5").value = reportScope;

  ["A3", "A4", "A5"].forEach(ref => {
    ws1.getCell(ref).font = { name: "Calibri", bold: true, size: 11 };
  });

  // --- Executive Summary ---
  const activeCount = customers.filter(c => c.status === "Active").length;
  const inactiveCount = customers.filter(c => c.status === "Inactive").length;
  const avgProgress = customers.length > 0 
    ? (customers.reduce((acc, c) => acc + (c.currentStamps / settings.purchasesRequired), 0) / customers.length) * 100
    : 0;
  
  const readyToRedeem = customers.filter(c => c.currentStamps >= settings.purchasesRequired).length;
  const totalRedeemed = customers.reduce((acc, c) => {
    return acc + c.recentActivity.filter(a => a.action.includes("Redeemed")).length;
  }, 0);

  ws1.getCell("D3").value = "Total Members (Scope)";
  ws1.getCell("D4").value = customers.length;
  
  ws1.getCell("E3").value = "Active Cards";
  ws1.getCell("E4").value = activeCount;

  ws1.getCell("F3").value = "Inactive Cards";
  ws1.getCell("F4").value = inactiveCount;

  ws1.getCell("G3").value = "Avg. Progress";
  ws1.getCell("G4").value = `${avgProgress.toFixed(1)}%`;

  ws1.getCell("H3").value = "Ready to Redeem";
  ws1.getCell("H4").value = readyToRedeem;

  ws1.getCell("I3").value = "Rewards Redeemed";
  ws1.getCell("I4").value = totalRedeemed;

  // Format Summary Cards
  ["D", "E", "F", "G", "H", "I"].forEach(col => {
    const header = ws1.getCell(`${col}3`);
    const value = ws1.getCell(`${col}4`);
    
    header.font = { name: "Calibri", size: 10, color: { argb: "555555" } };
    header.fill = { type: "pattern", pattern: "solid", fgColor: { argb: neutralBgColor } };
    header.alignment = { horizontal: "center" };
    header.border = { top: { style: "thin" }, left: { style: "thin" }, right: { style: "thin" } };

    value.font = { name: "Calibri", size: 14, bold: true, color: { argb: brandColor } };
    value.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFFF" } };
    value.alignment = { horizontal: "center" };
    value.border = { bottom: { style: "thin" }, left: { style: "thin" }, right: { style: "thin" } };
  });

  // --- Data Table ---
  const startRow = 11;
  const columns = [
    { header: "Customer Name", key: "name", width: 25 },
    { header: "Email Address", key: "email", width: 30 },
    { header: "Card Number", key: "cardNumber", width: 25 },
    { header: "Current Stamps", key: "currentStamps", width: 15 },
    { header: "Required Stamps", key: "requiredStamps", width: 15 },
    { header: "Progress (%)", key: "progressPct", width: 15 },
    { header: "Membership Date", key: "membershipDate", width: 20 },
    { header: "Card Status", key: "status", width: 15 },
    { header: "Lifetime Purchases", key: "lifetimePurchases", width: 18 },
    { header: "Rewards Redeemed", key: "rewardsRedeemed", width: 18 },
    { header: "Last Activity", key: "lastActivity", width: 25 },
  ];

  // Set Headers
  columns.forEach((col, index) => {
    const cell = ws1.getCell(startRow, index + 1);
    cell.value = col.header;
    cell.font = { name: "Calibri", bold: true, color: { argb: "333333" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: neutralBgColor } };
    cell.border = { 
      top: { style: "thin" }, bottom: { style: "thin" },
      left: { style: "thin" }, right: { style: "thin" } 
    };
    cell.alignment = { vertical: "middle", horizontal: "center" };
    ws1.getColumn(index + 1).width = col.width;
  });

  ws1.autoFilter = {
    from: { row: startRow, column: 1 },
    to: { row: startRow, column: columns.length }
  };

  // Populate Data
  customers.forEach((customer, index) => {
    const row = ws1.getRow(startRow + 1 + index);
    
    const progressPct = (customer.currentStamps / settings.purchasesRequired) * 100;
    const rewardsRedeemed = customer.recentActivity.filter(a => a.action.includes("Redeemed")).length;
    const lastActivity = customer.recentActivity.length > 0 ? customer.recentActivity[0].date : "None";
    const memDate = new Date(customer.membershipDate).toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' });

    row.values = [
      customer.name,
      customer.email,
      customer.cardNumber,
      customer.currentStamps,
      settings.purchasesRequired,
      progressPct / 100, // Format as Excel percentage
      memDate,
      customer.status,
      customer.lifetimePurchases,
      rewardsRedeemed,
      lastActivity
    ];

    // Zebra striping & Formatting
    row.eachCell({ includeEmpty: true }, (cell, colNumber) => {
      cell.font = { name: "Calibri", size: 11 };
      cell.border = { 
        top: { style: "thin", color: { argb: "E5E7EB" } }, 
        bottom: { style: "thin", color: { argb: "E5E7EB" } },
        left: { style: "thin", color: { argb: "E5E7EB" } }, 
        right: { style: "thin", color: { argb: "E5E7EB" } } 
      };

      if (index % 2 === 1) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "F9FAFB" } };
      }

      // Percentage formatting for Progress (%)
      if (colNumber === 6) {
        cell.numFmt = "0%";
      }
      // Text format for Card Number to prevent scientific notation
      if (colNumber === 3) {
        cell.numFmt = "@"; 
        cell.alignment = { horizontal: "center" };
      }
      // Center align specific columns
      if ([4, 5, 8, 9, 10].includes(colNumber)) {
        cell.alignment = { horizontal: "center" };
      }
    });
  });

  // Conditional Formatting for Progress (%)
  ws1.addConditionalFormatting({
    ref: `F12:F${startRow + customers.length}`,
    rules: [
      { type: 'cellIs', priority: 1, operator: 'greaterThan', formulae: ['0.799'], style: { font: { color: { argb: '166534' } }, fill: { type: 'pattern', pattern: 'solid', bgColor: { argb: 'DCFCE7' } } } }, // Green >= 80%
      { type: 'cellIs', priority: 2, operator: 'between', formulae: ['0.5', '0.799'], style: { font: { color: { argb: '9A3412' } }, fill: { type: 'pattern', pattern: 'solid', bgColor: { argb: 'FFEDD5' } } } }, // Orange 50-79%
      { type: 'cellIs', priority: 3, operator: 'lessThan', formulae: ['0.5'], style: { font: { color: { argb: '991B1B' } }, fill: { type: 'pattern', pattern: 'solid', bgColor: { argb: 'FEE2E2' } } } } // Red < 50%
    ]
  });

  // Conditional Formatting for Card Status
  ws1.addConditionalFormatting({
    ref: `H12:H${startRow + customers.length}`,
    rules: [
      { type: 'containsText', priority: 4, operator: 'containsText', text: 'Active', style: { font: { color: { argb: '166534' } }, fill: { type: 'pattern', pattern: 'solid', bgColor: { argb: 'DCFCE7' } } } },
      { type: 'containsText', priority: 5, operator: 'containsText', text: 'Inactive', style: { font: { color: { argb: '1F2937' } }, fill: { type: 'pattern', pattern: 'solid', bgColor: { argb: 'F3F4F6' } } } }
    ]
  });

  // Footer
  const footerRow = startRow + customers.length + 2;
  ws1.mergeCells(`A${footerRow}:K${footerRow}`);
  const footer1 = ws1.getCell(`A${footerRow}`);
  footer1.value = "Report generated by Sheilz Coffee Web Administration (Frontend Preview Only)";
  footer1.font = { name: "Calibri", size: 9, italic: true, color: { argb: "888888" } };
  footer1.alignment = { horizontal: "center" };

  const footerRow2 = footerRow + 1;
  ws1.mergeCells(`A${footerRow2}:K${footerRow2}`);
  const footer2 = ws1.getCell(`A${footerRow2}`);
  footer2.value = "End of Report";
  footer2.font = { name: "Calibri", size: 9, bold: true, color: { argb: "888888" } };
  footer2.alignment = { horizontal: "center" };


  // =========================================================================
  // WORKSHEET 2: Loyalty Program Settings
  // =========================================================================
  const ws2 = workbook.addWorksheet("Loyalty Program Settings");

  ws2.columns = [
    { width: 30 },
    { width: 30 }
  ];

  ws2.mergeCells("A1:B1");
  const ws2Title = ws2.getCell("A1");
  ws2Title.value = "Loyalty Program Configuration";
  ws2Title.font = { name: "Calibri", size: 16, bold: true, color: { argb: headerFontColor } };
  ws2Title.fill = { type: "pattern", pattern: "solid", fgColor: { argb: brandColor } };
  ws2Title.alignment = { vertical: "middle", horizontal: "center" };

  const settingsData = [
    { label: "Purchases Required for Reward", value: settings.purchasesRequired },
    { label: "Reward Type", value: settings.reward },
    { label: "Reward Quantity", value: settings.rewardQuantity },
    { label: "Program Status", value: settings.enabled ? "Enabled" : "Disabled" },
    { label: "Last Modified", value: `${dateString} ${timeString} (Placeholder)` },
    { label: "Last Modified By", value: `${adminName} (Placeholder)` }
  ];

  settingsData.forEach((item, index) => {
    const row = ws2.getRow(index + 3);
    row.getCell(1).value = item.label;
    row.getCell(1).font = { name: "Calibri", bold: true };
    row.getCell(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: neutralBgColor } };
    
    row.getCell(2).value = item.value;
    row.getCell(2).font = { name: "Calibri" };
    
    row.eachCell((cell) => {
      cell.border = { 
        top: { style: "thin", color: { argb: "E5E7EB" } }, 
        bottom: { style: "thin", color: { argb: "E5E7EB" } },
        left: { style: "thin", color: { argb: "E5E7EB" } }, 
        right: { style: "thin", color: { argb: "E5E7EB" } } 
      };
      cell.alignment = { vertical: "middle", horizontal: "left" };
    });
  });

  // Live Preview
  ws2.mergeCells("A11:B11");
  const previewTitle = ws2.getCell("A11");
  previewTitle.value = "Live Promotion Preview";
  previewTitle.font = { name: "Calibri", bold: true, size: 12, color: { argb: brandColor } };
  previewTitle.alignment = { horizontal: "center" };

  ws2.mergeCells("A12:B15");
  const previewBox = ws2.getCell("A12");
  previewBox.value = `Buy ${settings.purchasesRequired} Drinks\nGet ${settings.rewardQuantity} ${settings.reward}`;
  previewBox.font = { name: "Calibri", bold: true, size: 18, color: { argb: "FFFFFF" } };
  previewBox.fill = { type: "pattern", pattern: "solid", fgColor: { argb: brandColor } };
  previewBox.alignment = { horizontal: "center", vertical: "middle", wrapText: true };
  
  // =========================================================================
  // EXPORT WORKBOOK
  // =========================================================================
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
  
  const nowForFile = new Date();
  const formattedDate = nowForFile.toISOString().split("T")[0];
  const formattedTime = nowForFile.toTimeString().split(" ")[0].replace(/:/g, "-").substring(0, 5);
  const fileName = `Sheilz_Customer_Report_${formattedDate}_${formattedTime}.xlsx`;
  
  saveAs(blob, fileName);
};
