import * as ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import { AuditLog } from "./data";
import { formatIpAddress, formatDevice } from "./utils";
import type { AuditFilters } from "./actions";

const PRIMARY_COLOR = "FFC2456A";

const headerStyle: Partial<ExcelJS.Style> = {
  font: { bold: true, color: { argb: "FFFFFFFF" } },
  fill: {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: PRIMARY_COLOR },
  },
  alignment: { vertical: "middle", horizontal: "center" },
  border: {
    top: { style: "thin", color: { argb: "FFCCCCCC" } },
    left: { style: "thin", color: { argb: "FFCCCCCC" } },
    bottom: { style: "thin", color: { argb: "FFCCCCCC" } },
    right: { style: "thin", color: { argb: "FFCCCCCC" } },
  },
};

const borderStyle: Partial<ExcelJS.Borders> = {
  top: { style: "thin", color: { argb: "FFEEEEEE" } },
  left: { style: "thin", color: { argb: "FFEEEEEE" } },
  bottom: { style: "thin", color: { argb: "FFEEEEEE" } },
  right: { style: "thin", color: { argb: "FFEEEEEE" } },
};

function getSeverityColor(severity: string): string {
  switch (severity) {
    case "Low":
      return "FF10B981"; // Green
    case "Medium":
      return "FFF59E0B"; // Orange
    case "High":
      return "FFEF4444"; // Red
    case "Critical":
      return "FF991B1B"; // Dark Red
    default:
      return "FF6B7280"; // Gray
  }
}

function formatDate(dateString: string): string {
  const d = new Date(dateString);
  return d.toLocaleString("en-US", {
    month: "short",
    day: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  }).replace(",", "");
}

export async function exportAuditToExcel(
  logs: AuditLog[],
  filters: AuditFilters,
  currentDate: Date = new Date(),
  userNameOptions: { id: string; name: string }[] = []
) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Sheilz Coffee POS";
  wb.created = currentDate;
  wb.modified = currentDate;

  const dateStr = currentDate.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  if (logs.length === 0) {
    const ws = wb.addWorksheet("Audit Summary");
    ws.getCell("A1").value = "Sheilz Coffee";
    ws.getCell("A1").font = { size: 20, bold: true, color: { argb: PRIMARY_COLOR } };
    ws.getCell("A2").value = "System Audit Report";
    ws.getCell("A2").font = { size: 14, bold: true, color: { argb: "FF4B5563" } };
    ws.getCell("A4").value = "Generated On";
    ws.getCell("B4").value = dateStr;
    ws.getCell("A6").value = "No audit log records were found for the selected filters.";
    ws.getCell("A6").font = { italic: true, color: { argb: "FF6B7280" } };
    ws.getColumn("A").width = 30;
    ws.getColumn("B").width = 20;
    await downloadWorkbook(wb, filters);
    return;
  }

  // --- Worksheet 1: Audit Summary ---
  const ws1 = wb.addWorksheet("Audit Summary");
  ws1.getColumn("A").width = 25;
  ws1.getColumn("B").width = 35;

  ws1.getCell("A1").value = "Sheilz Coffee";
  ws1.getCell("A1").font = { size: 20, bold: true, color: { argb: PRIMARY_COLOR } };
  ws1.getCell("A2").value = "System Audit Report";
  ws1.getCell("A2").font = { size: 14, bold: true, color: { argb: "FF4B5563" } };

  ws1.getCell("A4").value = "Generated On";
  ws1.getCell("B4").value = dateStr;
  ws1.getCell("A5").value = "Generated By";
  ws1.getCell("B5").value = "System User";

  ["A4", "A5"].forEach((cell) => {
    ws1.getCell(cell).font = { bold: true };
    ws1.getCell(cell).alignment = { horizontal: "left" };
  });

  const uniqueUsers = new Set(logs.map((l) => l.user_name)).size;
  const categoriesLogged = new Set(logs.map((l) => l.category)).size;

  let low = 0, medium = 0, high = 0, critical = 0;
  logs.forEach(l => {
    if (l.severity === "Low") low++;
    if (l.severity === "Medium") medium++;
    if (l.severity === "High") high++;
    if (l.severity === "Critical") critical++;
  });

  ws1.getCell("A7").value = "Audit Statistics";
  ws1.getCell("A7").font = { size: 12, bold: true, color: { argb: PRIMARY_COLOR } };

  const metricsRowStart = 8;
  const metrics = [
    { label: "Total Audit Records", val: logs.length },
    { label: "Unique Users", val: uniqueUsers },
    { label: "Categories Logged", val: categoriesLogged },
    { label: "Low Severity Events", val: low },
    { label: "Medium Severity Events", val: medium },
    { label: "High Severity Events", val: high },
    { label: "Critical Severity Events", val: critical },
  ];

  metrics.forEach((m, idx) => {
    const rowNum = metricsRowStart + idx;
    ws1.getCell(`A${rowNum}`).value = m.label;
    ws1.getCell(`B${rowNum}`).value = m.val;
    ws1.getCell(`A${rowNum}`).font = { bold: true };
    ws1.getCell(`B${rowNum}`).alignment = { horizontal: "right" };
  });

  const filtersStart = metricsRowStart + metrics.length + 1;
  ws1.getCell(`A${filtersStart}`).value = "Applied Filters";
  ws1.getCell(`A${filtersStart}`).font = { size: 12, bold: true, color: { argb: PRIMARY_COLOR } };

  const filterHeaderRow = filtersStart + 1;
  ws1.getCell(`A${filterHeaderRow}`).value = "Filter";
  ws1.getCell(`B${filterHeaderRow}`).value = "Value";
  ws1.getRow(filterHeaderRow).eachCell((cell, colNumber) => {
    if (colNumber <= 2) cell.style = headerStyle as ExcelJS.Style;
  });

  const activeFilters = [];
  if (filters.search) activeFilters.push({ label: "Search", val: filters.search });
  
  if (filters.userId && filters.userId !== "All") {
    const uName = userNameOptions.find(u => u.id === filters.userId)?.name || filters.userId;
    activeFilters.push({ label: "User", val: uName });
  } else {
    activeFilters.push({ label: "User", val: "All" });
  }

  activeFilters.push({ label: "Category", val: filters.category || "All" });
  activeFilters.push({ label: "Action", val: filters.action || "All" });
  activeFilters.push({ label: "Severity", val: filters.severity || "All" });
  
  if (filters.datePreset && filters.datePreset !== "All") {
    activeFilters.push({ label: "Date Range", val: filters.datePreset });
    if (filters.datePreset === "Custom") {
      activeFilters.push({ label: "Start Date", val: filters.customStartDate || "" });
      activeFilters.push({ label: "End Date", val: filters.customEndDate || "" });
    }
  } else {
    activeFilters.push({ label: "Date Range", val: "All Time" });
  }

  activeFilters.forEach((f, idx) => {
    const rowNum = filterHeaderRow + 1 + idx;
    ws1.getCell(`A${rowNum}`).value = f.label;
    ws1.getCell(`B${rowNum}`).value = f.val;
    ws1.getRow(rowNum).getCell(1).font = { bold: true };
    ws1.getRow(rowNum).eachCell((cell, colNum) => {
      if (colNum <= 2) cell.border = borderStyle as ExcelJS.Borders;
    });
  });

  // --- Worksheet 2: Audit Log Records ---
  const ws2 = wb.addWorksheet("Audit Log Records", {
    views: [{ state: "frozen", ySplit: 1 }],
  });
  ws2.columns = [
    { header: "Timestamp", key: "timestamp", width: 22 },
    { header: "User", key: "user", width: 20 },
    { header: "Category", key: "category", width: 18 },
    { header: "Action", key: "action", width: 22 },
    { header: "Target", key: "target", width: 30 },
    { header: "Severity", key: "severity", width: 15 },
    { header: "IP Address", key: "ip", width: 18 },
    { header: "Device", key: "device", width: 25 },
  ];

  ws2.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  logs.forEach((log) => {
    const targetDisplay = log.target_name ? `${log.target_type}: ${log.target_name}` : "-";
    const row = ws2.addRow({
      timestamp: formatDate(log.created_at),
      user: log.user_name,
      category: log.category,
      action: log.action,
      target: targetDisplay,
      severity: log.severity,
      ip: formatIpAddress(log.ip_address),
      device: formatDevice(log.device),
    });

    row.eachCell((cell) => {
      cell.border = borderStyle as ExcelJS.Borders;
    });

    const severityCell = row.getCell("severity");
    severityCell.font = { bold: true, color: { argb: getSeverityColor(log.severity) } };
  });
  ws2.autoFilter = `A1:H${logs.length + 1}`;

  // --- Worksheet 3: Activity Summary ---
  const ws3 = wb.addWorksheet("Activity Summary");
  ws3.columns = [
    { header: "Category", key: "category", width: 25 },
    { header: "Total Events", key: "total", width: 18 },
  ];
  ws3.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  const categoryCounts = new Map<string, number>();
  logs.forEach(l => {
    categoryCounts.set(l.category, (categoryCounts.get(l.category) || 0) + 1);
  });
  const sortedCategories = Array.from(categoryCounts.entries()).sort((a, b) => b[1] - a[1]);

  let r3 = 2;
  sortedCategories.forEach(([cat, count]) => {
    const row = ws3.addRow({ category: cat, total: count });
    row.eachCell(c => { c.border = borderStyle as ExcelJS.Borders; });
    r3++;
  });
  const totalsRow3 = ws3.addRow({ category: "TOTALS", total: { formula: `SUM(B2:B${r3 - 1})` } });
  totalsRow3.font = { bold: true };
  totalsRow3.eachCell(c => {
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF3F4F6" } };
    c.border = borderStyle as ExcelJS.Borders;
  });

  // --- Worksheet 4: User Activity Summary ---
  const ws4 = wb.addWorksheet("User Activity Summary");
  ws4.columns = [
    { header: "User", key: "user", width: 25 },
    { header: "Total Actions", key: "total", width: 18 },
  ];
  ws4.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  const userCounts = new Map<string, number>();
  logs.forEach(l => {
    userCounts.set(l.user_name, (userCounts.get(l.user_name) || 0) + 1);
  });
  const sortedUsers = Array.from(userCounts.entries()).sort((a, b) => b[1] - a[1]);

  let r4 = 2;
  sortedUsers.forEach(([usr, count]) => {
    const row = ws4.addRow({ user: usr, total: count });
    row.eachCell(c => { c.border = borderStyle as ExcelJS.Borders; });
    r4++;
  });
  const totalsRow4 = ws4.addRow({ user: "TOTALS", total: { formula: `SUM(B2:B${r4 - 1})` } });
  totalsRow4.font = { bold: true };
  totalsRow4.eachCell(c => {
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF3F4F6" } };
    c.border = borderStyle as ExcelJS.Borders;
  });

  // --- Worksheet 5: Severity Summary ---
  const ws5 = wb.addWorksheet("Severity Summary");
  ws5.columns = [
    { header: "Severity", key: "severity", width: 20 },
    { header: "Events", key: "events", width: 15 },
    { header: "Percentage", key: "pct", width: 15 },
  ];
  ws5.getRow(1).eachCell((cell) => {
    cell.style = headerStyle as ExcelJS.Style;
  });

  const severityOrder = ["Low", "Medium", "High", "Critical"];
  const severityCounts = { Low: 0, Medium: 0, High: 0, Critical: 0 };
  logs.forEach(l => {
    if (l.severity in severityCounts) {
      severityCounts[l.severity as keyof typeof severityCounts]++;
    }
  });

  let r5 = 2;
  severityOrder.forEach(sev => {
    const count = severityCounts[sev as keyof typeof severityCounts];
    const pct = logs.length > 0 ? count / logs.length : 0;
    const row = ws5.addRow({ severity: sev, events: count, pct: pct });
    row.eachCell(c => { c.border = borderStyle as ExcelJS.Borders; });
    
    row.getCell("severity").font = { bold: true, color: { argb: getSeverityColor(sev) } };
    row.getCell("pct").numFmt = "0.00%";
    r5++;
  });

  // Footer for all sheets
  wb.eachSheet((sheet) => {
    sheet.headerFooter = {
      oddFooter: `&LSheilz Coffee POS - Audit Logs Report&CGenerated On ${dateStr}&RPage &P of &N`,
    };
  });

  await downloadWorkbook(wb, filters);
}

async function downloadWorkbook(
  wb: ExcelJS.Workbook,
  filters: AuditFilters,
) {
  const buffer = await wb.xlsx.writeBuffer();
  
  const isoDate = new Date().toISOString().split("T")[0];
  let fileName = `Audit_Logs_${isoDate}.xlsx`;
  
  if (filters.category && filters.category !== "All") {
    fileName = `Audit_Logs_${filters.category.replace(/\s+/g, "_")}.xlsx`;
  } else if (filters.severity && filters.severity !== "All") {
    fileName = `Audit_Logs_${filters.severity}_Severity.xlsx`;
  }

  saveAs(new Blob([buffer]), fileName);
}
